# Do not use this configuration in production.
# It is for demonstration purposes only.

env:
  GF_EXPLORE_ENABLED: true
  GF_PANELS_DISABLE_SANITIZE_HTML: true
  GF_LOG_FILTERS: rendering:debug
  GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
  GF_DATE_FORMATS_FULL_DATE: "MMM Do, YYYY hh:mm:ss a"
  GF_DATE_FORMATS_INTERVAL_SECOND: "hh:mm:ss a"
  GF_DATE_FORMATS_INTERVAL_MINUTE: "hh:mm a"
  GF_DATE_FORMATS_INTERVAL_HOUR: "DD/MM hh:mm a"
  GF_DATE_FORMATS_INTERVAL_DAY: "DD/MM"
  GF_DATE_FORMATS_INTERVAL_MONTH: "MM-YYYY"
  GF_DATE_FORMATS_INTERVAL_YEAR: "YYYY"
  GF_AUTH_ANONYMOUS_ENABLED: true
  GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  GF_AUTH_DISABLE_LOGIN_FORM: true

#adminPassword: admin

rbac:
  create: false
  pspEnabled: false

# Disable test pods
testFramework:
  enabled: false

podLabels:
  app: grafana

podAnnotations:
  "consul.hashicorp.com/connect-inject": "false"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus-server.dmetrics.svc.cluster.local:80/
        basicAuth: false
        version: 1
        editable: true
        isDefault: true
