# https://github.com/hashicorp/consul-k8s/blob/main/charts/consul/values.yaml
global:
  image: jjtimmons/consul:v3
  imageConsulDataplane: jjtimmons/consul-dataplane:v7

  datacenter: dc1
  logLevel: debug
  tls:
    enabled: false
    # enableAutoEncrypt: true
    # verify: true
  acls:
    manageSystemACLs: false
    # secretKey: "key"

  metrics:
    enabled: true
    enableAgentMetrics: true
    agentMetricsRetentionTime: "1m"

connectInject:
  enabled: true
  default: true

  # https://developer.hashicorp.com/consul/tutorials/service-mesh-observability/hashiconf-2023
  metrics:
    defaultEnabled: true

server:
  enabled: true
  replicas: 1
  extraConfig: |
    {
      "log_level": "DEBUG"
    }
