---
# Source: consul/templates/telemetry-collector-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: consul-telemetry-collector
  namespace: default
  labels:
    app: consul
    release: consul
    component: consul-telemetry-collector

spec:
  type: ClusterIP
  ports:
    - port: 9356
      targetPort: 9356
  selector:
    app: consul
    component: consul-telemetry-collector
---
# Source: consul/templates/telemetry-collector-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-telemetry-collector
  namespace: default
  labels:
    app: consul
    release: consul
    component: consul-telemetry-collector
---
# Source: consul/templates/telemetry-collector-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-telemetry-collector
  namespace: default
  labels:
    app: consul
    release: consul
    component: consul-telemetry-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
      release: consul
      component: consul-telemetry-collector
  template:
    metadata:
      labels:
        app: consul
        release: consul
        component: consul-telemetry-collector
        consul.hashicorp.com/connect-inject-managed-by: consul-k8s-endpoints-controller
      annotations:
        "consul.hashicorp.com/connect-inject": "false"
        "consul.hashicorp.com/connect-inject-status": "injected"
        # "consul.hashicorp.com/connect-service": "consul-telemetry-collector"
        "consul.hashicorp.com/connect-service-port": "metricsserver"
        "consul.hashicorp.com/transparent-proxy": "false"
        "consul.hashicorp.com/transparent-proxy-overwrite-probes": "false"
        "consul.hashicorp.com/connect-k8s-version": 1.2.2
    spec:
      # This needs to explicitly be consul-telemetry-collector because we look this up from each service consul-dataplane
      # to forward metrics to it.
      serviceAccountName: consul-telemetry-collector
      volumes:
        - name: consul-service
          emptyDir:
            medium: "Memory"
        - name: consul-ca-cert
          secret:
            secretName: consul-ca-cert
            items:
              - key: tls.crt
                path: tls.crt
        - name: config
          configMap:
            name: consul-telemetry-collector
      initContainers:
        # We're manually managing this init container instead of using the connect injector so that we don't run into
        # any race conditions on the connect-injector deployment or upgrade
        - name: consul-telemetry-collector-init
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CONSUL_LOGIN_AUTH_METHOD
              value: consul-k8s-auth-method
            - name: CONSUL_LOGIN_META
              value: "component=consul-telemetry-collector,pod=$(NAMESPACE)/$(POD_NAME)"
            - name: CONSUL_NODE_NAME
              value: $(NODE_NAME)-virtual
            - name: CONSUL_ADDRESSES
              value: consul-server.default.svc
            - name: CONSUL_GRPC_PORT
              value: "8502"
            - name: CONSUL_HTTP_PORT
              value: "8501"
            - name: CONSUL_DATACENTER
              value: dc1
            - name: CONSUL_API_TIMEOUT
              value: 5s
            - name: CONSUL_PARTITION
              value: default
            - name: CONSUL_LOGIN_PARTITION
              value: default
            - name: CONSUL_USE_TLS
              value: "true"
            - name: CONSUL_CACERT_FILE
              value: "/consul/tls/ca/tls.crt"
            - name: CONSUL_TLS_SERVER_NAME
              value: server.dc1.consul
            - name: CONSUL_NAMESPACE
              value: default
            - name: CONSUL_LOGIN_NAMESPACE
              value: "default"
          command:
            - /bin/sh
            - -ec
            - |
              consul-k8s-control-plane connect-init \
                -pod-name=${POD_NAME} \
                -pod-namespace=${POD_NAMESPACE} \
                -service-name="" \
                -service-account-name="consul-telemetry-collector" \
                -proxy-id-file=/consul/service/proxyid \
                -log-level=debug \
                -log-json=false
          image: hashicorp/consul-k8s-control-plane:1.2.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 50m
              memory: 150Mi
            requests:
              cpu: 50m
              memory: 25Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
              add:
                - NET_BIND_SERVICE
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 100
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: consul-service
              mountPath: /consul/service
            - name: consul-ca-cert
              mountPath: /consul/tls/ca
              readOnly: true
      containers:
        - name: consul-telemetry-collector
          image: hashicorp/consul-telemetry-collector:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              name: metrics
              protocol: TCP
            - containerPort: 9356
              name: metricsserver
              protocol: TCP
          env:
            # These are mounted as secrets so that the telemetry-collector can use them when cloud is enabled.
            # - the hcp-go-sdk in consul agent will already look for HCP_CLIENT_ID, HCP_CLIENT_SECRET, HCP_AUTH_URL,
            #   HCP_SCADA_ADDRESS, and HCP_API_HOST.  so nothing more needs to be done.
            # - HCP_RESOURCE_ID is created for use in the global cloud section but we will share it here
            - name: HCP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: consul-hcp-observability-client-id
                  key: client-id
            - name: HCP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: consul-hcp-observability-client-secret
                  key: client-secret
            - name: HCP_RESOURCE_ID
              valueFrom:
                secretKeyRef:
                  name: consul-hcp-resource-id
                  key: resource-id

          command:
            - "/bin/sh"
            - "-ec"
            - |

              consul-telemetry-collector agent \
          volumeMounts:
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 1000m
              memory: 512Mi
        # consul-dataplane container
        - name: consul-dataplane
          image: "hashicorp/consul-dataplane:1.2.2"
          imagePullPolicy: IfNotPresent
          command:
            - consul-dataplane
          args:
            - -addresses=consul-server.default.svc
            - -ca-certs=/consul/tls/ca/tls.crt
            - -credential-type=login
            - -envoy-concurrency=2
            - -grpc-port=8502
            - -log-json=false
            - -log-level=trace
            - -login-auth-method=consul-k8s-auth-method
            - -login-bearer-token-path=/var/run/secrets/kubernetes.io/serviceaccount/token
            - -login-namespace=default
            - -login-partition=default
            - -proxy-service-id-path=/consul/service/proxyid
            - -service-namespace=default
            - -service-partition=default
            - -telemetry-prom-scrape-path=/metrics
            - -tls-server-name=server.dc1.consul
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DP_CREDENTIAL_LOGIN_META1
              value: pod=$(NAMESPACE)/$(POD_NAME)
            - name: DP_CREDENTIAL_LOGIN_META2
              value: component=consul-telemetry-collector
            - name: DP_SERVICE_NODE_NAME
              value: $(NODE_NAME)-virtual
            - name: TMPDIR
              value: /consul/service
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 20000
            timeoutSeconds: 1
          securityContext:
            readOnlyRootFilesystem: true
            runAsGroup: 5995
            runAsNonRoot: true
            runAsUser: 5995
          # dataplane volume mounts
          volumeMounts:
            - name: consul-service
              mountPath: /consul/service
            - name: consul-ca-cert
              mountPath: /consul/tls/ca
              readOnly: true
