---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: a
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: a
spec:
  protocol: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: a
  labels:
    app: a
spec:
  selector:
    app: a
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a
  labels:
    app: a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a
  template:
    metadata:
      labels:
        app: a
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        # consul.hashicorp.com/connect-service-upstreams: "b:8080"
        consul.hashicorp.com/service-meta-version: "v1"
    spec:
      serviceAccountName: a
      containers:
        - name: a
          image: nicholasjackson/fake-service:v0.26.0
          # env:
          #   #  Comma separated URIs of the upstream services to call
          #   - name: UPSTREAM_URIS
          #     value: "http://localhost:8080"
          #   # Median duration for a request
          #   - name: TIMING_50_PERCENTILE
          #     value: "0.3s"
          #   - name: UPSTREAM_REQUEST_SIZE
          #     value: "1000"
          ports:
            - containerPort: 9090
