global:
  image: hashicorp/consul-enterprise:1.16.3-ent
  datacenter: dc2
  logLevel: debug

  peering:
    enabled: true

  server:
    exposeService:
      type: ClusterIP

  tls:
    enabled: true
    enableAutoEncrypt: true
    verify: false

  acls:
    manageSystemACLs: true
    bootstrapToken:
      secretName: consul-bootstrap-token
      secretKey: token

  enterpriseLicense:
    secretName: consul-license
    secretKey: license

  metrics:
    enableTelemetryCollector: true

  cloud:
    enabled: true
    clientId:
      secretKey: client-id
      secretName: consul-hcp-client-id
    clientSecret:
      secretKey: client-secret
      secretName: consul-hcp-client-secret
    resourceId:
      secretKey: resource-id
      secretName: consul-hcp-resource-id

connectInject:
  enabled: true
  default: true
  transparentProxy:
    defaultEnabled: true

dns:
  enabled: true
  enableRedirection: true

server:
  enabled: true
  replicas: 1
  extraConfig: |
    {
      "log_level": "DEBUG"
    }

meshGateway:
  enabled: true
  replicas: 1
  service:
    type: ClusterIP

terminatingGateways:
  enabled: false

ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer

telemetryCollector:
  enabled: true
  cloud:
    clientId:
      secretKey: client-id
      secretName: consul-hcp-client-id
    clientSecret:
      secretKey: client-secret
      secretName: consul-hcp-client-secret
