---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: b
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: b
spec:
  protocol: "http"
---
apiVersion: v1
kind: Service
metadata:
  name: b
  labels:
    app: b
spec:
  selector:
    app: b
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: b
  labels:
    app: b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: b
  template:
    metadata:
      labels:
        app: b
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/service-meta-version: "v1"
    spec:
      serviceAccountName: b
      containers:
        - name: b
          image: nicholasjackson/fake-service:v0.26.0
          env:
            - name: TIMING_50_PERCENTILE
              value: "0.15s"
          ports:
            - containerPort: 9090
